# Generated by Django 3.2.4 on 2021-08-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/avatars/profile.jpg', upload_to='avatars/'),
        ),
    ]
